[package]
name = "generic_type_params_trait_bounds_and_lifetimes_together"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
